# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af454dd56b940a980f1b6124c61dcfb1706bd1a0a91780ddf6f1097063402a86859051c64afc35727533528eda2db45ab247b3cfe9fee13f2408446fdd2fe1fd

test:
  secret_key_base: 88e5bae3deb2bb1bdce2eb00a55b8806853adb6d1640316818e4761ed582900e97f6cf2d2f0ccc79291f5c6bfa904e735e36276f5392bab340f381fc4e6e16c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
